# Generated by Django 5.2.6 on 2025-09-30 18:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Movie title you want to create a petition for', max_length=300)),
                ('description', models.TextField(help_text='Why should this movie be added?', validators=[django.core.validators.MinLengthValidator(50)])),
                ('movie_year', models.IntegerField(blank=True, help_text='Release year', null=True)),
                ('director', models.CharField(blank=True, help_text='Director name (optional)', max_length=100)),
                ('genre', models.CharField(blank=True, help_text='Movie genre optional', max_length=50)),
                ('imdb_link', models.URLField(blank=True, help_text='IMDB link optional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending REVIEW'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Movie Added')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_petitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='petitions.petition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
